function m(V){throw V;}var t=true,u=null,x=false;
(function(){function V(f,b){function a(){this.constructor=f}for(var c in b)if(Ba.call(b,c))f[c]=b[c];a.prototype=b.prototype;f.prototype=new a;f.Oa=b.prototype}function s(f,b){return function(){return f.apply(b,arguments)}}var ma,na,Z,la,aa,ia,oa,pa,ja,qa,ra,sa,ta,ka,W,ua,D,j,va,fa,wa,ga,ba=Array.prototype.slice,Ba=Object.prototype.hasOwnProperty,Ca=Array.prototype.indexOf||function(f){for(var b=0,a=this.length;b<a;b++)if(this[b]===f)return b;return-1};aa=x;j={Xa:7,ub:"#main-canvas",kb:"#dragged-canvas",
mc:"#selector",jc:"#palette",Ta:"auto",jb:$.browser.webkit&&"-webkit-grab"||$.browser.hc&&"-moz-grab"||"auto",Vb:$.browser.webkit&&"-webkit-grabbing"||$.browser.hc&&"-moz-grabbing"||"auto",lb:10,q:101,ha:Math.floor(50.5),Q:Math.floor(Math.floor(50.5)/2),v:707,z:707,sc:"img/textures.png",qb:0.7,na:0.3,wc:0.3,bc:0.995,j:50};W=function(f,b,a){return Math.abs(f-b)<a};ma=function(f,b){var a;if(f.length!==b.length)return x;for(a in f)if(f[a]!==b[a])return x;return t};fa=function(f,b,a){return Math.sqrt(f*
f+b*b+a*a)};D=function(f){return f<0?-1:f>0?1:0};ga=Array.isArray||function(f){return Object.prototype.toString.call(f)==="[object Array]"};ia=function(){function f(){}f.prototype.Db=function(b){if(!this.events)this.events={};this.events.vb=b};f.prototype.t=function(){var b,a,c,d,e;b=arguments[0];c=2<=arguments.length?ba.call(arguments,1):[];if(b==="error"){if(!this.events||!this.events.error||ga(this.events.error)&&!this.events.error.length)c[0]instanceof Error?m(new c[0]):m(Error("Uncaught, unspecified 'error' event."));
return x}b=(a=this.events)!=u?a[b]:void 0;if(!b)return x;if(typeof b==="function"){switch(arguments.length){case 1:b.call(this);break;case 2:b.call(this,c[0]);break;case 3:b.call(this,c[0],c[1]);break;default:b.apply(this,c)}return t}else if(ga(b)){e=b.slice();b=0;for(d=e.length;b<d;b++){a=e[b];a.apply(this,c)}return t}else return x};f.prototype.M=function(b,a){var c;typeof a!=="function"&&m("addListener only takes instances of Function");if(!this.events)this.events={};this.t("newListener",b,a);if(this.events[b])if(ga(this.events[b])){this.events[b].tc||
(c=this.events.vb!=u?this.events.vb:10);if(c&&c>0&&this.events[b].length>c){this.events[b].tc=t;if(aa){console.error("Possible EventEmitter memory leak detected.");console.trace()}}this.events[b].push(a)}else this.events[b]=[this.events[b],a];else this.events[b]=a};f.prototype.xb=function(b){var a,c,d,e,g;typeof b!=="function"&&m("removeListener only takes instances of Function");if((a=this.events)!=u&&a.didChange){c=this.events.didChange;if(ga(c)){d=-1;a=0;for(e=c.length;0<=e?a<=e:a>=e;0<=e?a++:
a--)if(c[a]===b||((g=c[a])!=u?g.fc:void 0)===b){d=a;break}if(!(d<0)){c.splice(d,1);c.length===0&&delete this.events.didChange}}else if(c===b||(c!=u?c.fc:void 0)===b)delete this.events.didChange}};return f}();Z=function(){function f(b){var a,c,d;d=this.w={top:[u,0],middle:[u,0],low:[u,0]};for(a in d){c=d[a];this.w[a]=b[a]||c}this.db();this.Db(1)}f.Nb=function(b,a){var c;c=a.p("middle")[0];if(b.p("top")[0]){if(c==="drop-low")return x;if(c==="dive"||c==="exchange"||c==="exchange-alt")return x}return t};
V(f,ia);f.$a=function(b){f.Na[b]||m(Error("Unknown type "+b));return new f(f.Na[b])};f.prototype.K=function(b,a,c){if(b<0||a<0||c<0)m(Error("Illegal coordinates "+b+":"+a+":"+c));return this.A=[b,a,c]};f.prototype.k=function(){return this.A};f.prototype.db=function(){var b,a,c,d;d=this.w;for(b in d){c=d[b];a=c[0];c=c[1];a&&!(Ca.call(f.Components[b],a)>=0)&&m(Error("Unknown "+b+" type "+a));c!==0&&c!==90&&c!==180&&c!==270&&m(Error("Rotation must be multiple of 90, was "+a))}d=this.p("top")[0];a=this.p("middle")[0];
b=this.p("low")[0];d==="crossing-hole"&&a!=="drop-middle"&&a!=="drop-low"&&m(Error("Top type crossing with hole requires middle type drop, was "+a));if(d!=="crossing-hole"&&(a==="drop-middle"||a==="drop-low"))m(Error("Middle type drop requires top type crossing with hole, was "+d));b&&a==="drop-low"&&m(Error("Middle type "+a+" is incompatible with low type "+b))};f.prototype.nc=function(){var b;if(b==u)b=x;this.opacity=0.4;b||this.t("didChange")};f.prototype.Eb=function(b){var a;this.selected=b;if(a==
u)a=x;if(!a)return this.t("didChange")};f.prototype.Cb=function(b){this.Z=b};f.prototype.p=function(b){b!=="top"&&b!=="middle"&&b!=="low"&&m(Error("Unknown property "+b));return this.w[b]};f.prototype.setProperty=function(b,a,c,d){var e,g;if(d==u)d=x;g=this.p(b)[1];e={};if(c===u)c=g;e[b]=[a,c];this.cb(e,x);if(!d)return this.t("didChange")};f.prototype.cb=function(b,a){var c,d,e,g;d={};g=this.w;for(c in g){e=g[c];d[c]=b[c]||e}this.db(d);d=this.w;for(c in d){e=d[c];this.w[c]=b[c]||e}a||this.t("didChange")};
f.prototype.Bb=function(){return this.rotate(t)};f.prototype.Ab=function(){return this.rotate(x)};f.prototype.rotate=function(b,a,c,d,e){var g,h,i,l,k,n;if(a==u)a=t;if(c==u)c=t;if(d==u)d=t;if(e==u)e=x;l=this.w.top;n=l[0];k=l[1];h=this.w.middle;l=h[0];i=h[1];g=this.w.low;h=g[0];g=g[1];b?this.cb({top:a?[n,(k+90)%360]:void 0,middle:c?[l,(i+90)%360]:void 0,low:d?[h,(g+90)%360]:void 0},t):this.cb({top:a?[n,(k+270)%360]:void 0,middle:c?[l,(i+270)%360]:void 0,low:d?[h,(g+270)%360]:void 0},t);if(!e)return this.t("didChange")};
f.prototype.toString=function(){var b,a,c,d,e;a=this.w.top;d=a[0];c=a[1];b=this.w.middle;a=b[0];b=b[1];e=this.w.low;return""+d+c+(""+a+b)+(""+e[0]+e[1])+(""+this.opacity+this.selected)};f.Components={top:["crossing","crossing-hole","curve","straight"],middle:["crossing","curve","straight","dive","drop-middle","drop-low","exchange-alt","exchange"],low:["crossing","curve","straight"]};f.Na={blank:{},"crossing-hole":{top:["crossing-hole",270],middle:["drop-middle",0]},"crossing-hole-alt":{top:["crossing-hole",
270],middle:["drop-low",0]},"double-straight":{top:["straight",0],middle:["straight",0]},"curve-straight":{top:["curve",270],middle:["straight",0]},"curve-straight-alt":{top:["curve",180],middle:["straight",0]},"double-curve":{top:["curve",270],middle:["curve",0]},"double-curve-alt":{top:["curve",90],middle:["curve",0]},"curve-exchange":{top:["curve",270],middle:["exchange",0]},"curve-exchange-alt":{top:["curve",180],middle:["exchange-alt",0]},"straight-exchange":{top:["straight",0],middle:["exchange",
0]},"straight-exchange-alt":{top:["straight",0],middle:["exchange-alt",0]},"curve-dive":{top:["curve",270],middle:["dive",0]},"curve-dive-alt":{top:["curve",0],middle:["dive",0]},"crossing-straight":{top:["crossing",270],middle:["straight",0]}};return f}();sa=function(){function f(b){this.D=b!=u?b:7;b=[-5E3,-5E3,0];this.x=b[0];this.y=b[1];this.Jb=b[2];b=[0,0,0];this.Hb=b[0];this.Ib=b[1];this.Kb=b[2]}f.prototype.K=function(b,a,c){var d;b!=u&&a!=u&&c!=u||m(Error("Missing parameter"));return d=[b,a,
c],this.x=d[0],this.y=d[1],this.Jb=d[2],d};f.prototype.k=function(){return[this.x,this.y,this.Jb]};f.prototype.Da=function(b,a,c){var d;b!=u&&a!=u&&c!=u||m(Error("Missing parameter"));return d=[b,a,c],this.Hb=d[0],this.Ib=d[1],this.Kb=d[2],d};f.prototype.pb=function(){return[this.Hb,this.Ib,this.Kb]};f.prototype.ea=function(b){b==u&&m(Error("Missing parameter"));isNaN(b)&&m(Error("Must not be NaN"));this.R=b};return f}();ka=function(){function f(){var a,c,d,e,g,h;e=1<=arguments.length?ba.call(arguments,
0):[];this.J={};g=0;for(h=e.length;g<h;g++){d=e[g];c=d.toString();this.J[c]=this.J[c]!=u?b.Mb(this.J[c],d):d}this.Ya=[];c=this.J;for(a in c){d=c[a];this.Ya.push(d)}}var b;f.Za=function(a){var c,d,e,g,h,i,l,k;l=a.k();c=l[0];d=l[1];e=l[2];k=a.p("top");l=k[0];k=k[1];g=a.p("middle");a=g[0];g=g[1];i=function(n,o,p,q){switch(n){case 90:return[p,j.j-o,q];case 180:return[j.j-o,j.j-p,q];case 270:return[j.j-p,o,q];default:return[o,p,q]}};h=function(n,o){var p,q,r,y,G,E,B;p={};for(G in n){E=n[G];y=E[0];q=E[1];
r=E[2];4<=E.length&&ba.call(E,3);y*=j.j;q*=j.j;r*=j.j;r=i(o,y,q,r);y=r[0];q=r[1];r=r[2];y+=j.j*c;q+=j.j*d;r+=j.j*e;p[G]=new b(y,q,r)}for(G in n){y=n[G];r=4<=y.length?ba.call(y,3):[];y=p[G];E=0;for(B=r.length;E<B;E++){q=r[E];y.X(p[q])}}q=[];for(G in p){y=p[G];q.push(y)}return q};l=h(f.fb.top[l],k);a=h(f.fb.gc[a],g);return ba.call(l).concat(ba.call(a))};f.ic=function(a){var c;c=[];a.F(s(function(d){var e,g,h,i;h=f.Za(d);i=[];e=0;for(g=h.length;e<g;e++){d=h[e];i.push(c.push(d))}return i},this));return c};
f.vc=function(a){return function(c,d,e){e.prototype=c.prototype;e=new e;c=c.apply(e,d);return typeof c==="object"?c:e}(f,this.Za(a),function(){})};f.nb=function(a){return function(c,d,e){e.prototype=c.prototype;e=new e;c=c.apply(e,d);return typeof c==="object"?c:e}(f,this.ic(a),function(){})};f.prototype.U=function(a,c,d){return this.J[""+a+":"+c+":"+d]||u};f.prototype.rotate=function(){var a,c,d,e;d={};e=this.J;for(a in e){c=e[a];rotateNode(c);d[c.toString()]=c}this.J=d;this.Ya=[];d=this.J;e=[];
for(a in d){c=d[a];e.push(this.Ya.push(c))}return e};b=function(){function a(c,d,e){this.A=[c,d,e]}a.Mb=function(c,d){var e,g,h;ma(c.k(),d.k())||m(Error("Node must be at same position."));c===d&&m(Error("Cannot join node with itself."));if(c.G().length===2||d.G().length===2)m(Error("Resulting node would have a degree bigger than 2."));h=function(i,l,k){k.prototype=i.prototype;k=new k;i=i.apply(k,l);return typeof i==="object"?i:k}(a,c.k(),function(){});e=c.G()[0];g=d.G()[0];h.X(e);h.X(g);e!=u&&e.yb(c)&&
e.X(h);g!=u&&g.yb(d)&&g.X(h);return h};a.prototype.K=function(c,d,e){return this.A=[c,d,e]};a.prototype.k=function(){return this.A};a.prototype.X=function(c){this.H&&this.I&&m(Error("Maximum degree for a node is two"));if(this.H==u)this.H=c;else if(this.I==u)this.I=c};a.prototype.G=function(){return this.H&&this.I?[this.H,this.I]:this.H?[this.H]:this.I?[this.I]:[]};a.prototype.yb=function(c){if(this.H===c){this.H=u;return t}else if(this.I===c){this.I=u;return t}else return x};a.prototype.toString=
function(){var c;c=this.A;return""+c[0]+":"+c[1]+":"+c[2]};return a}();f.fb={top:{straight:{a:[0,0.5,1,"b"],b:[1,0.5,1,"a"]},crossing:{a:[0,0.5,1,"b"],b:[1,0.5,1,"a"],c:[0.5,0,1,"d"],d:[0.5,1,1,"c"]},curve:{a:[0,0.5,1,"b"],b:[0.125,0.5,1,"a","c"],c:[0.375,0.625,1,"b","d"],d:[0.5,0.875,1,"c","e"],e:[0.5,1,1,"d"]}},gc:{straight:{a:[0,0.5,0.5,"b"],b:[1,0.5,0.5,"a"]},crossing:{a:[0,0.5,0.5,"b"],b:[1,0.5,0.5,"a"],c:[0.5,0,0.5,"d"],d:[0.5,1,0.5,"c"]},curve:{a:[0,0.5,0.5,"b"],b:[0.125,0.5,0.5,"a","c"],c:[0.375,
0.625,0.5,"b","d"],d:[0.5,0.875,0.5,"c","e"],e:[0.5,1,0.5,"d"]},dive:{a:[0,0.5,0.5,"b"],b:[1,0.5,0.125,"a"]},exchange:{a:[0,0.5,0.5,"b"],b:[0.125,0.5,0.5,"a","c"],c:[0.375,0.625,0.25,"b","d"],d:[0.5,0.875,0.125,"c","e"],e:[0.5,1,0.125,"d"]},"exchange-alt":{a:[0,0.5,0.125,"b"],b:[0.125,0.5,0.125,"a","c"],c:[0.375,0.625,0.25,"b","d"],d:[0.5,0.875,0.5,"c","e"],e:[0.5,1,0.5,"d"]},"drop-middle":{a:[0,0.5,1,"m"],b:[1,0.5,1,"m"],c:[0.5,0,1,"m"],d:[0.5,1,1,"m"],m:[0.5,0.5,1,"e"],e:[0.5,0.5,0.75,"m","f"],
f:[0.375,0.5,0.625,"e","g"],g:[0.125,0.5,0.5,"f","h"],h:[0,0.5,0.5,"g"]},"drop-low":{a:[0,0.5,1,"m"],b:[1,0.5,1,"m"],c:[0.5,0,1,"m"],d:[0.5,1,1,"m"],m:[0.5,0.5,1,"e"],e:[0.5,0.5,0.5,"m","f"],f:[0.375,0.5,0.25,"e","g"],g:[0.125,0.5,0.125,"f","h"],h:[0,0.5,0.125,"g"]}}};return f}.call(this);qa=function(){function f(b){var a,c;1<b&&b<255||m(Error("Size must be between 1 and 255"));this.size=b;this.Db(2);this.T=Array(Math.pow(this.size,3));b=0;for(c=Math.pow(this.size,3);0<=c?b<c:b>c;0<=c?b++:b--)this.T[b]=
u;this.rotation=0;a=this;this.Ra=function(){return a.t("didChange")};this.t("didChange")}V(f,ia);f.prototype.ob=function(){this.t("didChange")};f.prototype.Ca=function(b,a,c,d,e){if(e==u)e=x;this.ka(a,c,d);b&&b.K(a,c,d);if(this.rotation){c=this.gb(a,c);a=c[0];c=c[1]}a=a+c*this.size+d*this.size*this.size;if((d=this.T[a])!=u)d.xb(this.Ra);this.T[a]=b;if((b=this.T[a])!=u)b.M("didChange",this.Ra);e||this.t("didChange")};f.prototype.u=function(b,a,c){this.ka(b,a,c);if(this.rotation){a=this.gb(b,a);b=a[0];
a=a[1]}return this.T[b+a*this.size+c*this.size*this.size]};f.prototype.kc=function(b,a,c,d){var e;if(d==u)d=x;e=this.u(b,a,c);this.Ca(u,b,a,c,t);e!=u&&e.xb(this.Ra);e!=u&&e.K(u,u,u);d||this.t("didChange");return e};f.prototype.rb=function(b,a){var c;this.ka(b,a,0);for(c=0;c<this.size&&this.u(b,a,c);)c++;return c};f.prototype.cc=function(b,a,c){var d,e,g;if(c==u)c=0;this.ka(b,a,c);if(c>(g=this.rb(b,a)))return[];d=[];for(e=c;c<=g?e<g:e>g;c<=g?e++:e--)d.push(this.u(b,a,e));return d};f.prototype.oc=function(b,
a,c,d){var e,g,h,i;if(d==u)d=0;if(e==u)e=x;this.ka(a,c,d);b.length-1+d<this.size||m(Error("Cannot place stack, height out of bounds"));h=0;for(i=b.length;h<i;h++){g=b[h];this.Ca(g,a,c,d++,t)}if(!e)return this.t("didChange")};f.prototype.lc=function(b,a,c){var d,e,g,h;if(c==u)c=0;if(d==u)d=x;g=this.cc(b,a,c);e=c;for(h=c+g.length;c<=h?e<h:e>h;c<=h?e++:e--)this.Ca(u,b,a,c++,t);d||this.t("didChange");return g};f.prototype.db=function(){return this.F(s(function(b){var a,c,d;d=b.k();a=d[0];c=d[1];d=d[2];
b&&d>0&&!this.u(a,c,d-1)&&m(Error("Encountered floating block at "+a+":"+c+":"+d))},this))};f.prototype.ka=function(b,a,c){0<=b&&b<this.size&&0<=a&&a<this.size&&0<=c&&c<this.size||m(Error("Index out of bounds "+b+":"+a+":"+c))};f.prototype.gb=function(b,a){switch(this.rotation){case 90:return[this.size-1-a,b];case 180:return[this.size-1-b,this.size-1-a];case 270:return[a,this.size-1-b];default:return[b,a]}};f.prototype.F=function(b){var a,c,d,e,g;c=this.size-1;for(g=[];c+1;){for(d=0;d<this.size;){for(e=
0;e<this.size;){if(a=this.u(c,d,e))b(a);e++}d++}g.push(c--)}return g};f.prototype.Sa=function(b){var a,c,d,e;a=this.size-1;for(e=[];a+1;){for(c=0;c<this.size;){for(d=0;d<this.size;){b(a,c,d);d++}c++}e.push(a--)}return e};f.prototype.Bb=function(){return this.rotate(t)};f.prototype.Ab=function(){return this.rotate(x)};f.prototype.rotate=function(b,a){var c,d,e,g,h,i,l;if(a==u)a=x;this.rotation=b?(this.rotation+90)%360:(this.rotation+270)%360;l=this.T;h=0;for(i=l.length;h<i;h++)if(c=l[h]){c.rotate(b,
t,t,t,t);g=c.k();d=g[0];e=g[1];g=g[2];e=b?[e,this.size-1-d]:[this.size-1-e,d];d=e[0];e=e[1];c.K(d,e,g)}if(!a)return this.t("didRotate",b)};return f}();va=function(){function f(b){var a,c,d;this.ia={};c=s(function(e){var g,h,i,l,k,n,o,p,q,r,y;p=0;r=f.Ma;y=[];for(o in r){n=r[o];y.push(function(){var G,E;E=[];for(k in n){l=n[k];aa&&console.log("loading "+o+"."+k);if((G=this.ia)[o]==u)G[o]={};this.ia[o][k]=Array(l);for(i=0;0<=l?i<l:i>l;0<=l?i++:i--){g=document.createElement("canvas");g.width=j.q;g.height=
j.q;h=g.getContext("2d");try{q=j.q;h.drawImage(e,i*q,p*q,q,q,0,0,q,q)}catch(B){if(aa){console.log("Encountered error "+B+" while loading texture: "+k);B.name==="INDEX_SIZE_ERR"&&console.log("Texture file may be too small")}break}this.ia[o][k][i]=g}E.push(p++)}return E}.call(this))}return y},this);a=s(function(){c(d);return b()},this);d=new Image;d.onload=a;d.src=j.sc}f.prototype.l=function(b,a,c){var d;if(!c)if(f.Ma[b][a]!=u)return this.ia[b][a][0];d=f.Ma[b][a];if(d==u)return u;return this.ia[b][a][c/
90%d]};f.Ma={basic:{hitbox:1,"floor-hitbox":1,solid:1,floor:1,backside:1,outline:1,"hole-middle":2,"hole-low":2,"hole-bottom":2},"cutouts-top":{crossing:1,curve:4,straight:2},"cutouts-bottom":{crossing:1,curve:4,straight:2},top:{crossing:1,"crossing-hole":1,curve:4,straight:2},middle:{crossing:1,curve:4,straight:2,dive:4,"drop-middle":4,"drop-low":4,"exchange-alt":4,exchange:4},low:{crossing:1,curve:4,straight:2}};return f}();ja=function(){function f(b,a){this.o=b;this.map=a;this.canvas=document.createElement("canvas");
this.canvas.width=j.z;this.canvas.height=j.v;this.context=this.canvas.getContext("2d");this.L=this.o.L}f.prototype.l=function(b,a,c){return this.L.l(b,a,c)};f.prototype.clear=function(){return this.context.clearRect(0,0,j.z,j.v)};return f}();pa=function(){function f(b,a){this.o=b;this.map=a;f.Oa.constructor.apply(this,arguments);this.floor=this.l("basic","floor-hitbox");this.dc=this.l("basic","hitbox")}V(f,ja);f.prototype.ga=function(b,a){var c;c=this.context.getImageData(b,a,1,1);if(c.data[0]>0)return"south";
if(c.data[1]>0)return"east";if(c.data[2]>0)return"top";if(c.data[3]>0)return"floor";return u};f.prototype.W=function(){this.clear();return this.map.Sa(s(function(b,a,c){var d,e,g;if(c===0){g=this.o.aa(b,a);e=g[0];g=g[1];this.context.drawImage(this.floor,e,g,j.q,j.q)}if((d=this.map.u(b,a,c))&&!d.Z){b=this.o.P(d);e=b[0];g=b[1];return this.context.drawImage(this.dc,e,g,j.q,j.q)}},this))};return f}();ra=function(){function f(b,a){this.o=b;this.map=a;f.Oa.constructor.apply(this,arguments);this.cache={}}
V(f,ja);f.prototype.W=function(){this.clear();this.Xb();return this.map.Sa(s(function(b,a,c){if(b=this.map.u(b,a,c))return this.N(this.context,b)},this))};f.prototype.Xb=function(){var b,a,c,d,e,g;g=[];c=0;for(e=this.map.size;0<=e?c<e:c>e;0<=e?c++:c--)g.push(function(){var h,i,l;l=[];d=0;for(h=this.map.size;0<=h?d<h:d>h;0<=h?d++:d--){i=this.o.aa(c,d);b=i[0];a=i[1];l.push(this.context.drawImage(this.l("basic","floor"),b,a,j.q,j.q))}return l}.call(this))};f.prototype.N=function(b,a,c,d){var e,g,h,i,
l,k,n,o,p,q,r,y;if(!(c!=u&&d!=u)){d=this.o.P(a);c=d[0];d=d[1]}i=a.toString();if(!(l=this.cache[i])){q=a.p("top");k=q[0];y=q[1];q=a.p("middle");o=q[0];h=q[1];l=a.p("low");q=l[0];p=l[1];this.cache[i]=l=document.createElement("canvas");l.height=l.width=j.q;i=l.getContext("2d");if(a.selected||a.opacity!==1){e=this.l("basic","backside");i.drawImage(e,0,0);if(q){e=this.l("low",q,p);e!=u&&i.drawImage(e,0,0)}if(o){e=this.l("middle",o,h);e!=u&&i.drawImage(e,0,0)}}i.globalAlpha=a.selected?0.3:a.opacity||1;
e=this.l("basic","solid");i.drawImage(e,0,0);i.globalAlpha=1;if(k){e=this.l("top",k,y);if(e!=u){if(a.selected)i.globalAlpha=0.6;i.drawImage(e,0,0);i.globalAlpha=1}}if(e=f.La[o]){g=0;for(n=e.length;g<n;g++){a=e[g];if((a+h)%360===0){r=this.l("basic","hole-middle",0);i.drawImage(r,0,0)}if((a+h)%360===90){a=this.l("basic","hole-middle",90);i.drawImage(a,0,0)}}}if(o=f.Ka[o]){e=0;for(g=o.length;e<g;e++){a=o[e];if((a+h)%360===0){n=this.l("basic","hole-low",0);i.drawImage(n,0,0)}if((a+h)%360===90){a=this.l("basic",
"hole-low",90);i.drawImage(a,0,0)}}}if(h=f.Lb[q]){o=0;for(e=h.length;o<e;o++){a=h[o];if((a+p)%360===0){g=this.l("basic","hole-bottom",0);i.drawImage(g,0,0)}if((a+p)%360===90){a=this.l("basic","hole-bottom",90);i.drawImage(a,0,0)}}}this.Yb(i);if(k=this.l("cutouts-top",k==="crossing-hole"?"crossing":k,y)){i.globalCompositeOperation="destination-out";i.drawImage(k,0,0);i.globalCompositeOperation="source-over"}if(k=this.l("cutouts-bottom",q,p)){i.globalCompositeOperation="destination-out";i.drawImage(k,
0,0);i.globalCompositeOperation="source-over"}}return b.drawImage(l,c,d)};f.prototype.Yb=function(b){b.drawImage(this.l("basic","outline"),0,0)};f.uc={straight:[0,180],curve:[0,90],crossing:[0,90,180,270]};f.La={crossing:[0,90,180,270],curve:[0,90],straight:[0,180],dive:[0],"drop-middle":[0],exchange:[0],"exchange-alt":[90]};f.Ka={dive:[180],"drop-low":[0],exchange:[90],"exchange-alt":[0]};f.Lb={straight:[0,180],curve:[0,90],crossing:[0,90,180,270]};return f}();wa=function(){function f(b,a,c){this.map=
b;this.o=a;this.i=c;f.Oa.constructor.call(this,this.map,this.o);this.cache={}}V(f,ja);f.prototype.W=function(){var b,a,c,d,e,g,h;this.clear();h=this.i.k();c=h[0];d=h[1];e=h[2];h=this.o.zb(this.i);b=h[0];a=h[1];g=this.i.D;return this.map.Sa(s(function(i,l,k){var n,o,p;if(!(i*j.j>=c+this.i.D||(l+1)*j.j<=d-this.i.D||(k+1)*j.j<=e-this.i.D))if(n=this.map.u(i,l,k)){p=this.o.P(n);o=p[0];p=p[1];if(o<=b+g&&b-g<b+j.q&&p<=a+g&&a-g<a+j.q)return(i+1)*j.j<c-g||l*j.j>d+g||k*j.j>e+g?this.N(this.context,n,o,p):this.Zb(this.context,
n,o,p)}},this))};f.prototype.N=function(b,a,c,d){var e,g,h,i,l,k;e=a.toString();if(!(g=this.cache[e])){g=a.p("top");h=g[0];k=g[1];a.p("middle");g=a.p("low");a=g[0];l=g[1];this.cache[e]=g=document.createElement("canvas");g.height=g.width=j.q;e=g.getContext("2d");i=this.l("basic","hitbox");e.globalCompositeOperation="source-over";e.drawImage(i,0,0);h=this.l("cutouts-top",h==="crossing-hole"?"crossing":h,k);e.globalCompositeOperation="destination-out";h&&e.drawImage(h,0,0);(h=this.l("cutouts-bottom",
a,l))&&e.drawImage(h,0,0)}b.globalCompositeOperation="source-over";return b.drawImage(g,c,d)};f.prototype.Zb=function(b,a,c,d){var e,g,h,i,l,k,n;n=a.p("top");e=n[0];i=n[1];n=a.p("middle");h=n[0];n=n[1];l=a.p("low");a=l[0];l=l[1];b.globalCompositeOperation="source-over";b.drawImage(this.l("basic","hitbox"),c,d);b.globalCompositeOperation="destination-out";(k=this.l("top",e,i))&&b.drawImage(k,c,d);(e=this.l("cutouts-top",e==="crossing-hole"?"crossing":e,i))&&b.drawImage(e,c,d);(e=this.l("cutouts-bottom",
a,l))&&b.drawImage(e,c,d);if(i=f.La[h]){a=0;for(l=i.length;a<l;a++){e=i[a];if((e+n)%360===0){k=this.l("basic","hole-middle",0);b.drawImage(k,c,d)}if((e+n)%360===90){e=this.l("basic","hole-middle",90);b.drawImage(e,c,d)}}}if(i=f.Ka[h]){k=[];a=0;for(l=i.length;a<l;a++){e=i[a];if((e+n)%360===0){h=this.l("basic","hole-low",0);b.drawImage(h,c,d)}k.push((e+n)%360===90?(g=this.l("basic","hole-low",90),b.drawImage(g,c,d)):void 0)}return k}};f.La={crossing:[0,90,180,270],curve:[0,90],straight:[0,180],dive:[0],
"drop-middle":[0],exchange:[0],"exchange-alt":[90]};f.Ka={dive:[180],"drop-low":[0],exchange:[90],"exchange-alt":[0]};return f}();ua=function(){function f(b,a,c,d){this.ma=b;this.map=a;this.i=c;this.aa=s(this.aa,this);this.Fa=s(this.Fa,this);this.Ha=s(this.Ha,this);this.Ga=s(this.Ga,this);this.n=$(j.ub);this.n.attr("width",j.z);this.n.attr("height",j.v);this.Va=this.n.get(0).getContext("2d");this.canvas=document.createElement("canvas");this.canvas.width=j.z;this.canvas.height=j.v;this.context=this.canvas.getContext("2d");
this.Aa=document.createElement("canvas");this.Aa.width=j.z;this.Aa.height=j.v;this.O=this.Aa.getContext("2d");this.S=$(j.kb);this.Ub=this.S.get(0).getContext("2d");this.L=new va(s(function(){this.tb=new pa(this,this.map);this.Wa=new ra(this,this.map);this.eb=new wa(this,this.map,this.i);this.map.M("didChange",this.Ga);this.map.M("didRotate",this.Fa);this.ma.M("marble:moved",this.Ha);this.Fa();return d()},this))}f.prototype.clear=function(b){return b.clearRect(0,0,j.z,j.v)};f.prototype.Ga=function(){aa&&
console.log("Redrawing map");this.tb.W();this.Wa.W();this.eb.W();this.ec();return this.Gb()};f.prototype.Ha=function(){var b;this.clear(this.O);this.eb.W();b=s(function(a,c){var d,e;e=this.zb(c);d=e[0];e=e[1];a.beginPath();a.arc(d,e,c.D,0,Math.PI*2,t);a.closePath();return a.fill()},this);this.O.globalCompositeOperation="source-over";b(this.O,this.i);this.O.globalCompositeOperation="destination-out";this.O.globalAlpha=0.4;this.O.drawImage(this.eb.canvas,0,0,j.z,j.v);this.O.globalAlpha=1;return this.Gb()};
f.prototype.Fa=function(){this.Ga();return this.Ha()};f.prototype.ec=function(){var b;b=s(function(a,c){if(c==u)c=1;this.context.globalCompositeOperation="source-over";this.context.globalAlpha=c;return this.context.drawImage(a.canvas,0,0,j.z,j.v)},this);this.clear(this.context);b(this.Wa)};f.prototype.Gb=function(){this.clear(this.Va);this.Va.drawImage(this.canvas,0,0,j.z,j.v);return this.Va.drawImage(this.Aa,0,0,j.z,j.v)};f.prototype.N=function(b,a,c,d){if(c==u)c=0;if(d==u)d=0;return this.Wa.N(b,
a,c,d)};f.prototype.Wb=function(b){var a,c,d,e,g;a=j.q;c=b.length===1?j.q:j.q+j.ha*(b.length-1);this.S.attr("width",a);this.S.attr("height",c);g=[];d=0;for(e=b.length;d<e;d++){a=b[d];g.push(this.N(this.Ub,a,0,c-j.q-d*j.ha))}};f.prototype.bb=function(b,a){var c,d,e,g,h,i,l,k,n,o,p;if(!(0<b&&b<j.z&&0<a&&a<j.v))return{};l=this.ga(b,a);if(l==="floor"){l=[];c=0;for(e=this.map.size;0<=e?c<e:c>e;0<=e?c++:c--)for(d=g=this.map.size-1;g<=0?d<=0:d>=0;g<=0?d++:d--){i=this.aa(c,d);h=i[0];i=i[1];if(h<=b&&b<h+j.q&&
i<=a&&a<i+j.q){h=this.L.l("basic","floor-hitbox").getContext("2d").getImageData(b-h,a-i,1,1);if(h.data[3]>0)return{A:[c,d,0],fa:"floor"}}}return l}else if(l){p=[];c=0;for(k=this.map.size;0<=k?c<k:c>k;0<=k?c++:c--)for(d=n=this.map.size-1;n<=0?d<=0:d>=0;n<=0?d++:d--)for(e=o=this.map.size-1;o<=0?e<=0:e>=0;o<=0?e++:e--){g=this.map.u(c,d,e);if(!(!g||g.Z)){i=this.P(g);h=i[0];i=i[1];if(h<=b&&b<h+j.q&&i<=a&&a<i+j.q){h=this.L.l("basic","hitbox").getContext("2d").getImageData(b-h,a-i,1,1);if(h.data[3]>0)return{Y:g,
A:[c,d,e],fa:l}}}}return p}else return{}};f.prototype.ga=function(b,a){return this.tb.ga(b,a)};f.prototype.zb=function(b){var a,c;c=b.k();b=c[0];a=c[1];return[b+a,j.v-7*j.Q-(2*c[2]+b-a)/2]};f.prototype.P=function(b){var a,c;c=b.k();b=c[0];a=c[1];return[(b+a)*j.ha,j.v-3*j.Q-(2*c[2]+b-a+this.map.size)*j.Q]};f.prototype.aa=function(b,a){return[(b+a)*j.ha,j.v-3*j.Q-(b-a+this.map.size)*j.Q]};return f}();na=function(){function f(b,a){this.map=b;this.i=a;this.Ua=s(this.Ua,this);this.Ia=s(this.Ia,this);this.map.M("didChange",
this.Ia);this.map.M("didRotate",this.Ua);this.Ia()}V(f,ia);f.prototype.Ia=function(){var b,a,c,d;this.path=ka.nb(this.map);if(this.i.C){a=(c=this.path).U.apply(c,this.i.r.k());b=(d=this.path).U.apply(d,this.i.s.k())}if(a&&b&&this.i.B===this.Qa.apply(this,this.i.k())){this.i.r=a;return this.i.s=b}else{this.i.C=x;this.i.r=u;return this.i.s=u}};f.prototype.Ua=function(b){var a,c,d,e,g,h,i;a=function(l,k,n){return b?[k,j.j*j.Xa-l,n]:[j.j*j.Xa-k,l,n]};h=this.i.k();c=h[0];g=h[1];h=h[2];(i=this.i).K.apply(i,
a(c,g,h));this.path=ka.nb(this.map);if(this.i.C){c=(e=this.path).U.apply(e,a.apply(u,this.i.r.k()));a=(d=this.path).U.apply(d,a.apply(u,this.i.s.k()));if(c&&a){this.i.r=c;return this.i.s=a}else{this.i.C=x;this.i.r=u;return this.i.s=u}}else{e=this.i.pb();d=e[0];a=e[1];e=e[2];return b?this.i.Da(a,-d,e):this.i.Da(-a,d,e)}};f.prototype.Qa=function(b,a,c){b=Math.floor(b/(j.j+1));a=Math.floor(a/(j.j+1));c=Math.floor(c/(j.j+1));return 0<=b&&b<this.map.size&&0<=a&&a<this.map.size&&0<=c&&c<this.map.size?this.map.u(b,
a,c):u};f.prototype.Pa=function(b){return W(b,0,0.09)?0:b*j.bc};f.prototype.animate=function(){var b,a,c,d,e,g,h,i,l,k,n,o,p,q,r,y,G,E,B,Q,xa,ca,K,I,S,M,ya,O,P,F;Q=this.i.k();p=Q[0];q=Q[1];r=Q[2];Q=this.i.pb();O=Q[0];P=Q[1];F=Q[2];K=this.i.D;ca=[p,q,r];Q=ca[0];xa=ca[1];ca=ca[2];ya=function(w,v,A,C,z){var H,N,L,J,X,da,R,za,Y,ha,Aa,ea,T;T=C.k();C=T[0];ha=T[1];T=T[2];z=z.k();R=z[0];Y=z[1];ea=z[2];L=function(U,Da,Ea,Fa){return(Ea-Fa)/(U-Da)||0};z=function(U){return!isFinite(U)};J=L(R,C,Y,ha);H=function(U){return J*
U+Y-J*R};X=L(R,C,ea,T);N=function(U){return X*U+ea-X*R};da=L(Y,ha,ea,T);L=z(J)?W(R,w,3):W(v,H(w),4);za=z(X)?W(R,w,3):W(A,N(w),3);Aa=z(da)?W(Y,v,6):W(A,function(U){return da*U+ea-da*Y}(v),6);if(L&&za&&Aa){w=z(J)?R:w;v=z(J)?v:H(w);A=z(X)?A:N(w);return Math.min(R,C)-3<=w&&w<=Math.max(R,C)+3&&Math.min(Y,ha)-3<=v&&v<=Math.max(Y,ha)+3&&Math.min(ea,T)-8<=A&&A<=Math.max(ea,T)+2?[w,v,A]:u}else return u};if(!this.i.C){e=this.Qa(p,q,r-K-1);if(e!=u&&(F<=0||e!==this.i.B&&F>=0))s(function(){var w,v,A,C,z,H,N,L,
J,X,da;C=ka.Za(e);N=0;for(A=C.length;N<A;N++){H=C[N];J=H.G();v=0;for(L=J.length;v<L;v++){z=J[v];if(w=ya(p,q,r-K-1,H,z)){p=w[0];q=w[1];r=w[2];v=H.k();w=v[0];N=v[1];L=v[2];C=z.k();v=C[0];A=C[1];C=C[2];if(D(w-v)!==0&&D(w-v)===D(O)||D(N-A)!==0&&D(N-A)===D(P)||D(L-C)!==0&&D(L-C)===D(F)){z=[z,H];H=z[0];z=z[1]}J=e.p("top");J=J[0];if(J!=="crossing-hole"){O*=D(w-v);P*=D(N-A);F*=D(L-C)}this.i.ea(fa(O,P,F));this.i.B=e;this.i.r=(X=this.path).U.apply(X,z.k());this.i.s=(da=this.path).U.apply(da,H.k());this.i.C=
t;return}}}return this.i.C=x},this)()}if(this.i.C){this.i.B=this.Qa(p,q,r)||this.i.B;k=this.i.r.k();I=k[0];S=k[1];M=k[2];o=this.i.s.k();k=o[0];n=o[1];o=o[2];g=I-p;h=S-q;i=M-r;l=fa(g,h,i);if(l<this.i.D&&this.i.r.G().length===1&&this.i.r.G()[0]===this.i.s){y=this.i.B.k();a=y[0];c=y[1];d=y[2];y=a+D(I-k);G=c+D(S-n);E=d+D(M-o);if(0<=y&&y<this.map.size&&0<=G&&G<this.map.size&&0<=E&&E<this.map.size)b=this.map.u(y,G,E);if(b){I=[this.i.s,this.i.r];this.i.r=I[0];this.i.s=I[1];this.i.ea(this.i.R*j.na);k=this.i.r.k();
I=k[0];S=k[1];M=k[2];o=this.i.s.k();k=o[0];n=o[1];o=o[2];g=I-p;h=S-q;i=M-r;l=fa(g,h,i)}}b=Math.sqrt(g*g+h*h);b=Math.atan(!isNaN(i/b)?i/b:Infinity)/(Math.PI/2);this.i.ea(this.i.R-j.qb*b);this.i.ea(this.Pa(this.i.R));b=this.i.R;if(M>r&&r>o&&D(i/b)===-1||M<r&&r<o&&D(i/b)===1){I=[this.i.s,this.i.r];this.i.r=I[0];this.i.s=I[1];k=this.i.r.k();I=k[0];S=k[1];M=k[2];o=this.i.s.k();k=o[0];n=o[1];o=o[2];g=I-p;h=S-q;i=M-r}else if(r<M&&D(i/b)===-1){this.i.ea(0);r=o}if(l>this.i.R){B=l/this.i.R;p+=g/B;q+=h/B;r+=
i/B}else{l=[I,S,M];p=l[0];q=l[1];r=l[2];h=this.i.r.G();b=0;for(g=h.length;b<g;b++){l=h[b];if(l!==this.i.s)B=l}if(B){this.i.s=this.i.r;this.i.r=B}else{g=I-k;h=S-n;i=M-o;B=fa(g,h,i)/this.i.R;this.i.C=x;B=[g/B,h/B,i/B];O=B[0];P=B[1];F=B[2];this.i.r=u;this.i.s=u}}}if(!this.i.C){p+=O;q+=P;r+=F;F-=j.qb;this.map.F(s(function(w){var v,A,C,z,H;if(w!==this.i.B){w=w.k();a=w[0];c=w[1];d=w[2];if(this.i.B){v=this.i.B.k();w=v[0];A=v[1];v=v[2];if(a===w&&c===A&&d===v+1)return}v=p>=a*j.j&&p<(a+1)*j.j;w=q>=c*j.j&&q<
(c+1)*j.j;A=r>=d*j.j&&r<(d+1)*j.j;if(v&&w)if(r-K<(d+1)*j.j){r=Math.round(r/j.j)*j.j+K;F=-F*j.na;if(Math.abs(F)<0.5)F=0;H=t}if(v&&A){C=c*j.j;z=c*j.j+j.j/2;v=(c+1)*j.j;if(q+K>C&&q-K<v){P=-P*j.na;q=q<=z?Math.round(q/j.j)*j.j-K:Math.round(q/j.j)*j.j+K;H=t}}if(w&&A){A=a*j.j;v=a*j.j+j.j/2;w=(a+1)*j.j;if(p+K>A&&p-K<w){O=-O*j.na;p=p<=v?Math.round(p/j.j)*j.j-K:Math.round(p/j.j)*j.j+K;H=t}}if(H)return this.i.B=u}},this));if(r-this.i.D<0){r=this.i.D;F=-F*0.3;if(Math.abs(F)<0.5)F=0;this.i.B=u}if(r===ca){O=this.Pa(O);
P=this.Pa(P)}}this.i.K(p,q,r);this.i.Da(O,P,F);if(ca!==r||xa!==q||Q!==p)return this.t("marble:moved")};return f}();la=function(){function f(){}f.Ja=4;f.prototype.Ob=function(b){var a,c,d,e,g,h,i,l,k,n,o,p;c=[];e=d=0;for(k=b.size;0<=k?e<k:e>k;0<=k?e++:e--){g=0;for(n=b.size;0<=n?g<n:g>n;0<=n?g++:g--){h=0;for(o=b.size;0<=o?h<o:h>o;0<=o?h++:h--)if(a=b.u(e,g,h)){if(d>0){c.push(255);c.push((d&16711680)>>16);c.push((d&65280)>>8);c.push(d&255);d=0}p=this.ac(a);i=0;for(l=p.length;i<l;i++){a=p[i];c.push(a)}}else d++}}return this.$b(c)};
f.prototype.Sb=function(b,a){var c,d,e,g,h,i,l,k;try{e=this.Pb(b)}catch(n){m(n)}d=g=0;for(k=[];g<e.length-2;){if(e[g]===255){h=e[g+1]<<16|e[g+2]<<8|e[g+3];d+=h;g+=f.Ja}try{c=this.Qb(e.slice(g,g+f.Ja+1||9E9))}catch(o){m(o)}l=this.wb(d,a.size*a.size);h=l[0];i=l[1];i=this.wb(i,a.size);l=i[0];i=i[1];a.Ca(c,h,l,i);g+=f.Ja;k.push(d++)}};f.prototype.wb=function(b,a){return[Math.floor(b/a),b%a]};f.prototype.$b=function(b){var a,c,d,e,g,h;d=[];g=e=a=0;for(h=b.length;g<h;g++){c=b[g];e=e<<8|c;a++;if(a%3===0){d.push(this.mb(e));
e=0}}if(a%3){b=3-a%3;e<<=b*8;d.push(this.mb(e));b===1&&d.push("=");b===2&&d.push("==")}return d.join("")};f.prototype.Pb=function(b){var a,c,d;a=[];for(c=0;c<b.length;)if(b[c]==="=")c++;else{try{d=this.Rb(b.slice(c,c+4))}catch(e){m(e)}a.push((d&16711680)>>16);a.push((d&65280)>>8);a.push(d&255);c+=4}return a};f.prototype.ac=function(b){var a,c,d,e,g,h;a=[];d=b.p("top");g=d[0];e=d[1];c=b.p("middle");d=c[0];c=c[1];h=b.p("low");b=h[0];a.push(e/90<<4|c/90<<2|h[1]/90);a.push(f.la[g]||0);a.push(f.la[d]||
0);a.push(f.la[b]||0);return a};f.prototype.Qb=function(b){var a,c,d,e,g,h,i;e=b[0];i=f.la;for(h in i){a=i[h];if(a===b[1])g=h;if(a===b[2])d=h;if(a===b[3])c=h}return new Z({top:[g||u,90*((e&48)>>4)],middle:[d||u,90*((e&12)>>2)],low:[c||u,90*(e&3)]})};f.prototype.mb=function(b){try{return this.xa((b&16515072)>>18)+this.xa((b&258048)>>12)+this.xa((b&4032)>>6)+this.xa(b&63)}catch(a){m(a)}};f.prototype.Rb=function(b){var a;b.length!==4&&m(Error("Illegal chunk size, was "+b.length));try{return a=this.ua(b[0])<<
18|this.ua(b[1])<<12|this.ua(b[2])<<6|this.ua(b[3])}catch(c){m(c)}};f.prototype.xa=function(b){if(0<=b&&b<=25)return String.fromCharCode(65+b);if(26<=b&&b<=51)return String.fromCharCode(97+b-26);if(52<=b&&b<=61)return String.fromCharCode(48+b-52);if(b===62)return"-";if(b===63)return"_";m(Error("Invalid argument "+b+" must be smaller than 0x3F (63)"))};f.prototype.ua=function(b){var a;a=b.charCodeAt(0);if(65<=a&&a<=90)return a-65;if(97<=a&&a<=122)return a-97+26;if(48<=a&&a<=57)return a-48+52;if(a===
45)return 62;if(a===95)return 63;m(Error("Invalid argument, char must be of [A-Za-z0-9-_], was "+b))};f.la={straight:1,curve:2,crossing:3,exchange:4,"exchange-alt":5,dive:6,"crossing-hole":7,"drop-middle":8,"drop-low":9};return f}();oa=function(){function f(b){this.ab=s(this.ab,this);this.ja=s(this.ja,this);this.wa=s(this.wa,this);this.Ea=s(this.Ea,this);this.va=s(this.va,this);this.ra=s(this.ra,this);this.sa=s(this.sa,this);this.ta=s(this.ta,this);this.qa=s(this.qa,this);this.pa=s(this.pa,this);
this.oa=s(this.oa,this);this.map=new qa(j.Xa);if(window.state==u)window.state={};state.type="normal";this.xc=x;this.n=$(j.ub);this.S=$(j.kb);this.selector=$(j.mc);this.i=new sa;this.ma=new na(this.map,this.i);this.o=new ua(this.ma,this.map,this.i,s(function(){var a,c;this.n.bind("mouseup",this.ta);this.n.bind("mousemove",this.sa);this.n.bind("mousedown",this.ra);this.n.bind("touchstart",this.V(this.ra));this.n.bind("touchmove",this.V(this.sa));this.n.bind("touchend",this.V(this.ta));a=$("body");a.bind("mouseup",
this.qa);a.bind("mousemove",this.pa);a.bind("mousedown",this.oa);a.bind("touchstart",this.V(this.oa));a.bind("touchmove",this.V(this.pa));a.bind("touchend",this.V(this.qa));a=s(function(d){return s(function(){this.da(u);this.za();return d?this.map.Bb():this.map.Ab()},this)},this);$("#game .left").bind("mousedown",a(x));$("#game .right").bind("mousedown",a(t));a=s(function(d){return s(function(e){var g,h,i,l,k;g=state.info.A;i=g[0];l=g[1];k=g[2];g=this.map.u(i,l,k);if(k+1<this.map.size)h=this.map.u(i,
l,k+1);g.rotate(d,t,t,x);h&&h.rotate(d,x,x,t);e.preventDefault();return x},this)},this);this.selector.children(".left").bind("mousedown",a(x));this.selector.children(".right").bind("mousedown",a(t));this.map.M("didChange",this.ja);$(".run").bind("click",this.ab);this.yc=new ta(this.o,this.Ea);c=s(function(){this.ma.animate();return setTimeout(c,20)},this);setTimeout(c,20);return b()},this))}f.prototype.da=function(b){this.Ba&&this.Ba.Eb(x);(this.Ba=b)&&this.Ba.Eb(t)};f.prototype.Tb=function(b,a){if(b==
u)b=0;if(a==u)a=0;this.selector.css({display:"block",position:"absolute",top:this.n.offset().top+a,left:this.n.offset().left+b})};f.prototype.za=function(){return this.selector.css({display:"none"})};f.prototype.oa=function(){switch(state.type){case "normal":this.da(u);return this.za()}};f.prototype.pa=function(b){switch(state.type){case "dragging":return this.va(b)}};f.prototype.qa=function(b){switch(state.type){case "dragging":this.wa(b)}return x};f.prototype.ta=function(b){var a;switch(state.type){case "dragging":this.wa(b);
break;case "down":a=b.pageX-this.n.offset().left;b=b.pageY-this.n.offset().top;if(state.info.Y===this.o.bb(a,b).Y){this.da(state.info.Y);b=this.o.P(state.info.Y);a=b[0];b=b[1];this.Tb(a,b);state.type="normal"}break;case "normal":this.da(u);this.za();break;default:aa&&console.error("Illegal state",state.type)}return x};f.prototype.sa=function(b){var a,c,d;a=b.pageX-this.n.offset().left;c=b.pageY-this.n.offset().top;switch(state.type){case "down":if(Math.abs(state.hb-a)>j.lb||Math.abs(state.ib-c)>j.lb)this.qc();
break;case "dragging":this.va(b);break;case "normal":if(b.type!=="touchmove")(d=this.o.ga(a,c))&&d!=="floor"?this.n.css("cursor",j.jb):this.n.css("cursor",j.Ta)}if(this.o.ga(a,c)!==u)return b.preventDefault()};f.prototype.ra=function(b){var a,c,d;switch(state.type){case "normal":c=b.pageX-this.n.offset().left;d=b.pageY-this.n.offset().top;a=this.o.bb(c,d);if(a.Y){state.type="down";state.hb=c;state.ib=d;state.info=a;b.preventDefault()}}return t};f.prototype.va=function(b){var a,c,d,e,g,h,i;a=x;this.map.F(s(function(l){var k;
if(l.Z){(k=this.map).kc.apply(k,ba.call(l.k()).concat([t]));return a=t}},this));e=b.pageX-this.n.offset().left;g=b.pageY-this.n.offset().top;c=this.o.bb(e,g);i=c.A||[0,0,0];e=i[0];g=i[1];i=i[2];h=this.map.u(e,g,i);d=state.stack&&state.stack[0];$("body").css("cursor",j.Vb);if(c.fa==="floor"||c.fa==="top"&&this.map.rb(e,g)+state.stack.length<this.map.size+1&&Z.Nb(h,d)){this.sb();if(d)if(c.fa==="top"){h=h.p("top");b=h[0];h=h[1];d.setProperty("low",b==="crossing-hole"&&"crossing"||b,h,t)}else d.setProperty("low",
u,0,t);c=c.fa==="top"?1:0;return this.map.oc(state.stack,e,g,i+c)}else{a&&this.map.ob();return this.pc(b)}};f.prototype.qc=function(){var b,a;b=state.info.A;b=this.map.lc(b[0],b[1],b[2]);a=this.o.P(b[b.length-1]);this.Ea(b,{ba:state.hb-a[0],ca:state.ib-a[1]})};f.prototype.Ea=function(b,a){var c,d,e,g;this.da(u);this.za();state.stack=b;g=state.stack;d=0;for(e=g.length;d<e;d++){c=g[d];c.Cb(t)}this.o.Wb(state.stack);state.ba=a.ba;state.ca=a.ca;return state.type="dragging"};f.prototype.sb=function(){this.S.css("display",
"none")};f.prototype.pc=function(b){return this.S.css({display:"block",position:"absolute",top:b.pageY-state.ca,left:b.pageX-state.ba})};f.prototype.wa=function(){state.stack=[];this.map.F(s(function(b){if(b.Z)return b.Cb(x)},this));this.map.ob();state.type="normal";$("body").css("cursor",j.Ta);this.sb();return this.Fb()};f.prototype.Fb=function(){var b;b=0;this.map.F(s(function(a){if(!a.Z){a=a.k();a=a[2];if(a>b)return b=a}},this));return this.n.css({"margin-top":-50+(-5+b)*j.ha})};f.prototype.V=
function(b){return function(a){if(a.originalEvent.touches&&a.originalEvent.touches[0]){a.pageX=a.originalEvent.touches[0].pageX;a.pageY=a.originalEvent.touches[0].pageY}return b(a)}};f.prototype.ja=function(){var b;b=x;this.map.F(s(function(a){if(!b)return b=a.p("top")[0]==="crossing-hole"},this));$(".run").toggleClass("inactive",!b);return $(".inserter").remove()};f.prototype.ab=function(){$(".inserter").remove();$(".popup").removeClass("visible");this.ja();if($(".run").hasClass("inactive")){$("#warning").addClass("visible");
return $("#warning .dismiss").bind("click",s(function(){return $("#warning").removeClass("visible")},this))}else return this.map.F(s(function(b){var a,c,d,e,g;if(b.p("top")[0]==="crossing-hole"){a=b.k();d=a[0];e=a[1];g=a[2];a=this.o.P(b);b=a[0];c=a[1];a=$('<div class="inserter" alt="Drop marble here!"></div>');a.css({top:this.n.offset().top+c-j.Q,left:this.n.offset().left+b+j.Q});a.bind("click",s(function(){d*=j.j;e*=j.j;g*=j.j;d+=j.j/2;e+=j.j/2;g+=j.j*3;this.i.Da(0,0,0);this.i.K(d,e,g);this.i.C=
x;return $(".inserter").remove()},this));return $("body").append(a)}},this))};return f}();ta=function(){return function(f,b){var a,c,d,e,g,h,i,l;this.o=f;this.rc=b!=u?b:function(){};c=$(j.jc);l=Z.Na;for(i in l){d=Z.$a(i);d.nc();g=document.createElement("canvas");g.width=j.q;g.height=j.q;a=g.getContext("2d");this.o.N(a,d);this.L=this.o.L;a=$("<img>");a.data("type",i);a.attr("src",g.toDataURL());c.append(a);e=this.rc;a.bind("mousedown",function(k){var n;n={ba:k.pageX-$(this).offset().left,ca:k.pageY-
$(this).offset().top};d=Z.$a($(this).data("type"));e([d],n);return k.preventDefault()});a.bind("touchstart",function(k){var n;if(k.originalEvent.touches.length){n={ba:k.originalEvent.touches[0].pageX-$(this).offset().left,ca:k.originalEvent.touches[0].pageY-$(this).offset().top};d=Z.$a($(this).data("type"));e([d],n);return k.preventDefault()}});h=this.L;a.bind("mousemove",function(k){var n;if(state.type==="normal"){n=k.pageX-$(this).offset().left;k=k.pageY-$(this).offset().top;n=h.l("basic","hitbox").getContext("2d").getImageData(n,
k,1,1);n.data[3]>0?$("body").css("cursor",j.jb):$("body").css("cursor",j.Ta);return x}})}}}();$(document).ready(function(){return this.ya=new oa(s(function(){var f,b;if(window.location.hash.length>1)try{f=new la;f.Sb(window.location.hash.slice(1),this.ya.map);this.ya.Fb()}catch(a){aa&&console.error("Coudl not parse map correctly: "+a)}this.ya.ja();$("#share input").focus(function(){return this.select()});$(".network.button").bind("click",function(c){c.preventDefault();c=$(this).attr("href");return window.open(c,
"popup","location=1,width=600,height=290,toolbar=no,scrollbars=no")});b=function(c){c=encodeURI(c).replace("#","%23");$(".facebook").attr({href:"http://facebook.com/sharer.php?u="+c});return $(".twitter").attr({href:"http://twitter.com/share?text=I've+built+a+marble+run+with+%23marbleous,+check+it+out&url="+c})};return $(".button.share").bind("click",s(function(){var c,d;$(".popup").removeClass("visible");f=new la;c=f.Ob(this.ya.map);d="http://marbleo.us/#"+c;window.location.replace("#"+c);$("#share input").val(d);
b(d);$("#share").addClass("visible");$("#share .dismiss").bind("click",function(){return $("#share").removeClass("visible")});return $.ajax({url:"http://api.bitly.com/v3/shorten",data:{format:"json",login:"robertboehnke",apiKey:"R_787e723dc060169b3bfde946beef129a",longUrl:d},success:function(e){if(e.status_code===200){$("#share input").val(e.data.url);return b(e.data.url)}}})},this))},this))})}).call(this);
