function l(p){throw p;}var o=true,q=null,r=false;
(function(){function p(f,b){return function(){return f.apply(b,arguments)}}var u,w,y,z,A,B,C=Array.prototype.indexOf||function(f){for(var b=0,a=this.length;b<a;b++)if(this[b]===f)return b;return-1};z=function(){function f(b){var a;if(!(1<b&&b<255))l(Error("Size must be between 1 and 255"));this.size=b;this.Q=Array(Math.pow(this.size,3));b=0;for(a=Math.pow(this.size,3);0<=a?b<a:b>a;0<=a?b+=1:b-=1)this.Q[b]=q;this.rotation=0;this.i(o)}f.prototype.T=function(b,a,c,d){this.B(a,c,d);if(this.rotation){c=
this.ka(a,c);a=c[0];c=c[1]}this.Q[a+c*this.size+d*this.size*this.size]=b;return this.i(o)};f.prototype.h=function(b,a,c){this.B(b,a,c);if(this.rotation){a=this.ka(b,a);b=a[0];a=a[1]}return this.Q[b+a*this.size+c*this.size*this.size]};f.prototype.Ya=function(b,a,c){var d;d=this.h(b,a,c);this.T(q,b,a,c);return d};f.prototype.ra=function(b,a){var c;this.B(b,a,0);for(c=0;c<this.size&&this.h(b,a,c);)c++;return c};f.prototype.Ua=function(b,a,c){var d,e,g;if(c==q)c=0;this.B(b,a,c);if(c>(g=this.ra(b,a)))return[];
d=[];for(e=c;c<=g?e<g:e>g;c<=g?e+=1:e-=1)d.push(this.h(b,a,e));return d};f.prototype.bb=function(b,a,c,d){var e,g,i,h;if(d==q)d=0;this.B(a,c,d);if(!(b.length-1+d<this.size))l(Error("Cannot place stack, height out of bounds"));h=[];g=0;for(i=b.length;g<i;g++){e=b[g];h.push(this.T(e,a,c,d++))}return h};f.prototype.Za=function(b,a,c){var d,e,g;if(c==q)c=0;e=this.Ua(b,a,c);d=c;for(g=c+e.length;c<=g?d<g:d>g;c<=g?d+=1:d-=1)this.T(q,b,a,d);return e};f.prototype.ia=function(){return this.l(p(function(b,a,
c,d){if(b&&d>0&&!this.h(a,c,d-1))l(Error("Encountered floating block at "+a+":"+c+":"+d))},this))};f.prototype.B=function(b,a,c){if(!(0<=b&&b<this.size&&0<=a&&a<this.size&&0<=c&&c<this.size))l(Error("Index out of bounds "+b+":"+a+":"+c))};f.prototype.ka=function(b,a){switch(this.rotation){case 90:return[this.size-1-a,b];case 180:return[this.size-1-b,this.size-1-a];case 270:return[a,this.size-1-b];default:return[b,a]}};f.prototype.i=function(b){this.Wa=b};f.prototype.l=function(b){var a,c,d,e;a=this.size-
1;for(e=[];a+1;){for(c=0;c<this.size;){for(d=0;d<this.size;){b(this.h(a,c,d),a,c,d);d++}c++}e.push(a--)}return e};f.prototype.xa=function(){return this.rotate(o)};f.prototype.wa=function(){return this.rotate(r)};f.prototype.rotate=function(b){var a,c,d,e;this.rotation=b?(this.rotation+90)%360:(this.rotation+270)%360;e=this.Q;c=0;for(d=e.length;c<d;c++)(a=e[c])&&a.rotate(b);return this.i(o)};return f}();B=function(){function f(b,a,c){var d,e;this.map=b;this.onload=a;this.a=c!=q?c:{};b=f.j;for(d in b)this.a[d]=
this.a[d]||f.j[d];this.canvas=$(this.a.da);this.canvas.attr("width",this.a.s);this.canvas.attr("height",this.a.m);this.context=this.canvas.get(0).getContext("2d");this.ca=document.createElement("canvas");this.ca.width=this.a.s;this.ca.height=this.a.m;this.R=this.ca.getContext("2d");this.o=$(this.a.Y);this.Ma=this.o.get(0).getContext("2d");this.A={};this.ja={};d=p(function(){this.cb(e);return this.onload()},this);e=new Image;e.onload=d;e.src=this.a.gb}f.j={da:"#main-canvas",Y:"#dragged-canvas",b:101,
r:Math.floor(50.5),la:Math.floor(Math.floor(50.5)/2),m:707,s:707,gb:"img/textures.png",fb:101};f.prototype.cb=function(b){var a,c,d,e,g,i,h,k,j,m,n;j=0;m=f.W;n=[];for(k in m){h=m[k];n.push(function(){var s,t;t=[];for(g in h){e=h[g];(s=this.A)[k]!=q||(s[k]={});this.A[k][g]=Array(e);for(d=0;0<=e?d<e:d>e;0<=e?d+=1:d-=1){a=document.createElement("canvas");a.width=this.a.b;a.height=this.a.b;c=a.getContext("2d");try{i=this.a.fb;c.drawImage(b,d*i,j*i,i,i,0,0,this.a.b,this.a.b)}catch(x){break}this.A[k][g][d]=
a}t.push(j++)}return t}.call(this))}return n};f.prototype.k=function(b,a,c){return[(b+a)*this.a.r,this.a.m-3*this.a.la-(2*c+b-a+this.map.size)*this.a.la]};f.prototype.ha=function(b,a){var c;c=this.R.getImageData(b,a,1,1);return c.data[0]>0?"south":c.data[1]>0?"east":c.data[2]>0?"top":c.data[3]>0?"floor":q};f.prototype.fa=function(b,a){var c,d,e,g,i,h,k,j,m,n,s;if(!(0<b&&b<this.a.s&&0<a&&a<this.a.m))return{};k=this.ha(b,a);if(k==="floor"){k=[];c=0;for(e=this.map.size;0<=e?c<e:c>e;0<=e?c+=1:c-=1)for(d=
g=this.map.size-1;g<=0?d<=0:d>=0;g<=0?d+=1:d-=1){h=this.k(c,d,0);i=h[0];h=h[1];if(i<=b&&b<i+this.a.b&&h<=a&&a<h+this.a.b){i=this.c("basic","floor-hitbox").getContext("2d").getImageData(b-i,a-h,1,1);if(i.data[3]>0)return{n:[c,d,0],z:"floor"}}}return k}else if(k){s=[];c=0;for(j=this.map.size;0<=j?c<j:c>j;0<=j?c+=1:c-=1)for(d=m=this.map.size-1;m<=0?d<=0:d>=0;m<=0?d+=1:d-=1)for(e=n=this.map.size-1;n<=0?e<=0:e>=0;n<=0?e+=1:e-=1){g=this.map.h(c,d,e);if(!(!g||g.t)){h=this.k(c,d,e);i=h[0];h=h[1];if(i<=b&&
b<i+this.a.b&&h<=a&&a<h+this.a.b){i=this.c("basic","hitbox").getContext("2d").getImageData(b-i,a-h,1,1);if(i.data[3]>0)return{D:g,n:[c,d,e],z:k}}}}return s}else return{}};f.prototype.c=function(b,a,c){var d;if(!c)if(f.W[b][a]!=q)return this.A[b][a][0];d=f.W[b][a];if(d==q)return q;return this.A[b][a][c/90%d]};f.prototype.aa=function(b){if(b==q)b=r;if(!((this.ta||!this.map.Wa)&&!b)){this.ta=o;this.context.clearRect(0,0,this.a.s,this.a.m);this.R.clearRect(0,0,this.a.s,this.a.m);this.Pa();this.map.l(p(function(a,
c,d,e){if(a){d=this.k(c,d,e);c=d[0];return this.Z(this.context,a,c,d[1])}},this));this.Qa();this.map.i(r);this.ta=r}};f.prototype.Qa=function(){return this.map.l(p(function(b,a,c,d){var e,g;if(d===0){g=this.k(a,c,0);e=g[0];g=g[1];this.R.drawImage(this.c("basic","floor-hitbox"),e,g,this.a.b,this.a.b)}if(b&&!b.t){b=this.k(a,c,d);e=b[0];g=b[1];return this.R.drawImage(this.c("basic","hitbox"),e,g,this.a.b,this.a.b)}},this))};f.prototype.Pa=function(){var b,a,c,d,e,g;g=[];c=0;for(e=this.map.size;0<=e?
c<e:c>e;0<=e?c+=1:c-=1)g.push(function(){var i,h,k;k=[];d=0;for(i=this.map.size;0<=i?d<i:d>i;0<=i?d+=1:d-=1){h=this.k(c,d,0);b=h[0];a=h[1];k.push(this.context.drawImage(this.c("basic","floor"),b,a,this.a.b,this.a.b))}return k}.call(this));return g};f.prototype.Z=function(b,a,c,d){var e,g,i,h,k,j,m,n,s,t,x,v;if(c==q)c=0;if(d==q)d=0;h=a.toString();if(!(k=this.ja[h])){t=a.f("top");v=t[0];j=t[1];t=a.f("middle");n=t[0];i=t[1];k=a.f("low");t=k[0];s=k[1];this.ja[h]=k=document.createElement("canvas");k.height=
k.width=this.a.b;h=k.getContext("2d");if(a.selected||a.opacity!==1){e=this.c("basic","backside");h.drawImage(e,0,0,this.a.b,this.a.b);if(t){e=this.c("low",t,s);e!=q&&h.drawImage(e,0,0,this.a.b,this.a.b)}if(n){e=this.c("middle",n,i);e!=q&&h.drawImage(e,0,0,this.a.b,this.a.b)}}h.globalAlpha=a.selected?0.3:a.opacity||1;e=this.c("basic","solid");h.drawImage(e,0,0,this.a.b,this.a.b);h.globalAlpha=1;if(v){e=this.c("top",v,j);if(e!=q){if(a.selected)h.globalAlpha=0.6;h.drawImage(e,0,0,this.a.b,this.a.b);
h.globalAlpha=1}}if(e=f.Ea[n]){g=0;for(m=e.length;g<m;g++){a=e[g];if((a+i)%360===0){x=this.c("basic","hole-middle",0);h.drawImage(x,0,0,this.a.b,this.a.b)}if((a+i)%360===90){a=this.c("basic","hole-middle",90);h.drawImage(a,0,0,this.a.b,this.a.b)}}}if(n=f.Da[n]){e=0;for(g=n.length;e<g;e++){a=n[e];if((a+i)%360===0){m=this.c("basic","hole-low",0);h.drawImage(m,0,0,this.a.b,this.a.b)}if((a+i)%360===90){a=this.c("basic","hole-low",90);h.drawImage(a,0,0,this.a.b,this.a.b)}}}if(i=f.Ca[t]){n=0;for(e=i.length;n<
e;n++){a=i[n];if((a+s)%360===0){g=this.c("basic","hole-bottom",0);h.drawImage(g,0,0,this.a.b,this.a.b)}if((a+s)%360===90){a=this.c("basic","hole-bottom",90);h.drawImage(a,0,0,this.a.b,this.a.b)}}}this.Ra(h,0,0);v=v==="crossing-hole"?"crossing":v;if(j=this.c("cutouts-top",v,j)){h.globalCompositeOperation="destination-out";h.drawImage(j,0,0,this.a.b,this.a.b);h.globalCompositeOperation="source-over"}if(j=this.c("cutouts-bottom",t,s)){h.globalCompositeOperation="destination-out";h.drawImage(j,0,0,this.a.b,
this.a.b);h.globalCompositeOperation="source-over"}}return b.drawImage(k,c,d,this.a.b,this.a.b)};f.prototype.Ra=function(b,a,c){return b.drawImage(this.c("basic","outline"),a,c,this.a.b,this.a.b)};f.prototype.Oa=function(b){var a,c,d,e,g;a=this.a.b;c=b.length===1?this.a.b:this.a.b+this.a.r*(b.length-1);this.o.attr("width",a);this.o.attr("height",c);g=[];d=0;for(e=b.length;d<e;d++){a=b[d];g.push(this.Z(this.Ma,a,0,c-this.a.b-d*this.a.r))}return g};f.W={basic:{hitbox:1,"floor-hitbox":1,solid:1,floor:1,
backside:1,outline:1,"hole-middle":2,"hole-low":2,"hole-bottom":2},"cutouts-top":{crossing:1,curve:4,straight:2},"cutouts-bottom":{crossing:1,curve:4,straight:2},top:{crossing:1,"crossing-hole":1,curve:4,straight:2},middle:{crossing:1,curve:4,straight:2,dive:4,"drop-middle":4,"drop-low":4,"exchange-alt":4,exchange:4},low:{crossing:1,curve:4,straight:2}};f.hb={straight:[0,180],curve:[0,90],crossing:[0,90,180,270]};f.Ea={crossing:[0,90,180,270],curve:[0,90],straight:[0,180],dive:[0],"drop-middle":[0],
exchange:[0],"exchange-alt":[90]};f.Da={dive:[180],"drop-low":[0],exchange:[90],"exchange-alt":[0]};f.Ca={straight:[0,180],curve:[0,90],crossing:[0,90,180,270]};return f}();w=function(){function f(){}f.V=4;f.prototype.Ga=function(b){var a,c,d,e,g,i,h,k,j,m,n,s;c=[];e=d=0;for(j=b.size;0<=j?e<j:e>j;0<=j?e+=1:e-=1){g=0;for(m=b.size;0<=m?g<m:g>m;0<=m?g+=1:g-=1){i=0;for(n=b.size;0<=n?i<n:i>n;0<=n?i+=1:i-=1)if(a=b.h(e,g,i)){if(d>0){c.push(255);c.push((d&16711680)>>16);c.push((d&65280)>>8);c.push(d&255);
d=0}s=this.Ta(a);h=0;for(k=s.length;h<k;h++){a=s[h];c.push(a)}}else d++}}return this.Sa(c)};f.prototype.Ka=function(b,a){var c,d,e,g,i,h,k,j;try{e=this.Ha(b)}catch(m){l(m)}d=g=0;for(j=[];g<e.length-2;){if(e[g]===255){i=e[g+1]<<16|e[g+2]<<8|e[g+3];d+=i;g+=f.V}try{c=this.Ia(e.slice(g,g+f.V+1||9E9))}catch(n){l(n)}k=this.va(d,a.size*a.size);i=k[0];h=k[1];h=this.va(h,a.size);k=h[0];h=h=h[1];a.T(c,i,k,h);g+=f.V;j.push(d++)}return j};f.prototype.va=function(b,a){return[Math.floor(b/a),b%a]};f.prototype.Sa=
function(b){var a,c,d,e,g,i;d=[];g=e=a=0;for(i=b.length;g<i;g++){c=b[g];e=e<<8|c;a++;if(a%3===0){d.push(this.qa(e));e=0}}if(a%3){b=3-a%3;e<<=b*8;d.push(this.qa(e));b===1&&d.push("=");b===2&&d.push("==")}return d.join("")};f.prototype.Ha=function(b){var a,c,d;a=[];for(c=0;c<b.length;)if(b[c]==="=")c++;else{try{d=this.Ja(b.slice(c,c+4))}catch(e){l(e)}a.push((d&16711680)>>16);a.push((d&65280)>>8);a.push(d&255);c+=4}return a};f.prototype.Ta=function(b){var a,c,d,e,g,i;a=[];d=b.f("top");g=d[0];e=d[1];
c=b.f("middle");d=c[0];c=c[1];i=b.f("low");b=i[0];a.push(e/90<<4|c/90<<2|i[1]/90);a.push(f.C[g]||0);a.push(f.C[d]||0);a.push(f.C[b]||0);return a};f.prototype.Ia=function(b){var a,c,d,e,g,i,h,k,j;a=b[0];i=90*((a&48)>>4);e=90*((a&12)>>2);c=90*(a&3);j=f.C;for(k in j){a=j[k];if(a===b[1])h=k;if(a===b[2])g=k;if(a===b[3])d=k}return new u({top:[h||q,i],middle:[g||q,e],low:[d||q,c]})};f.prototype.qa=function(b){try{return this.P((b&16515072)>>18)+this.P((b&258048)>>12)+this.P((b&4032)>>6)+this.P(b&63)}catch(a){l(a)}};
f.prototype.Ja=function(b){var a;if(b.length!==4)l(Error("Illegal chunk size, was "+b.length));try{return a=this.L(b[0])<<18|this.L(b[1])<<12|this.L(b[2])<<6|this.L(b[3])}catch(c){l(c)}};f.prototype.P=function(b){if(0<=b&&b<=25)return String.fromCharCode(65+b);if(26<=b&&b<=51)return String.fromCharCode(97+b-26);if(52<=b&&b<=61)return String.fromCharCode(48+b-52);if(b===62)return"-";if(b===63)return"_";l(Error("Invalid argument "+b+" must be smaller than 0x3F (63)"))};f.prototype.L=function(b){var a;
a=b.charCodeAt(0);if(65<=a&&a<=90)return a-65;if(97<=a&&a<=122)return a-97+26;if(48<=a&&a<=57)return a-48+52;if(a===45)return 62;if(a===95)return 63;l(Error("Invalid argument, char must be of [A-Za-z0-9-_], was "+b))};f.C={straight:1,curve:2,crossing:3,exchange:4,"exchange-alt":5,dive:6,"crossing-hole":7,"drop-middle":8,"drop-low":9};return f}();y=function(){function f(b,a){this.O=p(this.O,this);this.U=p(this.U,this);this.N=p(this.N,this);this.I=p(this.I,this);this.J=p(this.J,this);this.K=p(this.K,
this);this.H=p(this.H,this);this.G=p(this.G,this);this.F=p(this.F,this);var c,d;this.a={};d=f.j;for(c in d)this.a[c]=b[c]||f.j[c];this.map=new z(this.a.Va);window.state!=q||(window.state={});state.type="normal";this.e=$(this.a.da);this.o=$(this.a.Y);this.selector=$(this.a.$a);this.d=new B(this.map,p(function(){var e;this.e.bind("mouseup",this.K);this.e.bind("mousemove",this.J);this.e.bind("mousedown",this.I);this.e.bind("touchstart",this.p(this.I));this.e.bind("touchmove",this.p(this.J));this.e.bind("touchend",
this.p(this.K));e=$("body");e.bind("mouseup",this.H);e.bind("mousemove",this.G);e.bind("mousedown",this.F);e.bind("touchstart",this.p(this.F));e.bind("touchmove",this.p(this.G));e.bind("touchend",this.p(this.H));$("#game .left").bind("mousedown",p(function(){this.map.wa();this.q(q);return this.u()},this));$("#game .right").bind("mousedown",p(function(){this.map.xa();this.q(q);return this.u()},this));this.selector.children(".left").bind("mousedown",p(function(g){var i,h,k,j,m;i=state.info.n;k=i[0];
j=i[1];m=i[2];i=this.map.h(k,j,m);if(m+1<this.map.size)h=this.map.h(k,j,m+1);i.rotate(r,o,o,r);h&&h.rotate(r,r,r,o);this.map.i(o);g.preventDefault();return r},this));this.selector.children(".right").bind("mousedown",p(function(g){var i,h,k,j,m;i=state.info.n;k=i[0];j=i[1];m=i[2];i=this.map.h(k,j,m);if(m+1<this.map.size)h=this.map.h(k,j,m+1);i.rotate(o,o,o,r);h&&h.rotate(o,r,r,o);this.map.i(o);g.preventDefault();return r},this));setInterval(p(function(){return this.d.aa()},this),20);this.ib=new A(this.d,
{Aa:this.U});return a()},this))}f.j={Va:7,da:"#main-canvas",Y:"#dragged-canvas",$a:"#selector",M:"auto",oa:$.browser.webkit&&"-webkit-grab"||$.browser.ua&&"-moz-grab"||"auto",Na:$.browser.webkit&&"-webkit-grabbing"||$.browser.ua&&"-moz-grabbing"||"auto",pa:10};f.prototype.q=function(b){this.S&&this.S.za(r);(this.S=b)&&this.S.za(o);return this.map.i(o)};f.prototype.La=function(b,a){if(b==q)b=0;if(a==q)a=0;return this.selector.css({display:"block",position:"absolute",top:this.e.offset().top+a,left:this.e.offset().left+
b})};f.prototype.u=function(){return this.selector.css({display:"none"})};f.prototype.F=function(){switch(state.type){case "normal":this.q(q);return this.u()}};f.prototype.G=function(b){switch(state.type){case "dragging":return this.N(b);default:return $("body").css("cursor",this.a.M)}};f.prototype.H=function(b){switch(state.type){case "dragging":this.O(b)}return r};f.prototype.K=function(b){var a,c;switch(state.type){case "dragging":this.O(b);break;case "down":a=b.pageX-this.e.offset().left;b=b.pageY-
this.e.offset().top;if(state.info.D===this.d.fa(a,b).D){this.q(state.info.D);a=(c=this.d).k.apply(c,state.info.n);c=a[0];a=a[1];this.La(c,a);state.type="normal"}break;case "normal":this.q(q);this.u()}return r};f.prototype.J=function(b){var a,c,d;a=b.pageX-this.e.offset().left;c=b.pageY-this.e.offset().top;switch(state.type){case "down":if(Math.abs(state.ma-a)>this.a.pa||Math.abs(state.na-c)>this.a.pa)this.eb(b);break;case "dragging":this.N(b);break;case "normal":if(b.type!=="touchmove")(d=this.d.ha(a,
c))&&d!=="floor"?$("body").css("cursor",this.a.oa):$("body").css("cursor",this.a.M)}if(this.d.ha(a,c)!==q)return b.preventDefault()};f.prototype.I=function(b){var a,c,d;switch(state.type){case "normal":c=b.pageX-this.e.offset().left;d=b.pageY-this.e.offset().top;a=this.d.fa(c,d);if(a.D){state.type="down";state.ma=c;state.na=d;state.info=a;b.preventDefault()}}return o};f.prototype.N=function(b){var a,c,d,e,g,i;this.map.l(p(function(h,k,j,m){var n;n=r;if(h&&h.t)if(this.map.Ya(k,j,m))n=o;if(n)return this.map.i(o)},
this));c=b.pageX-this.e.offset().left;a=b.pageY-this.e.offset().top;a=this.d.fa(c,a);c=a.n||[0,0,0];e=c[0];g=c[1];i=c[2];d=this.map.h(e,g,i);c=state.stack&&state.stack[0];if(a.z==="floor"||a.z==="top"&&this.map.ra(e,g)+state.stack.length<this.map.size+1&&u.Fa(d,c)){this.sa(b);b=a.z==="top"?1:0;this.map.bb(state.stack,e,g,i+b);if(a.z==="top"){a=d.f("top");b=a[0];a=a[1];b=b==="crossing-hole"&&"crossing"||b;c.setProperty("low",b,a)}else c.setProperty("low",q,0);return this.map.i(o)}else return this.db(b)};
f.prototype.eb=function(){var b,a,c,d;b=state.info.n;a=b[0];c=b[1];d=b[2];b=this.map.Za(a,c,d);a=this.d.k(a,c,d+b.length);this.U(b,{v:state.ma-a[0],w:state.na-a[1]-this.d.a.r});return this.d.aa(o)};f.prototype.U=function(b,a){var c,d,e,g;this.q(q);this.u();state.stack=b;g=state.stack;d=0;for(e=g.length;d<e;d++){c=g[d];c.ya(o)}this.d.Oa(state.stack);state.v=a.v;state.w=a.w;return state.type="dragging"};f.prototype.sa=function(){return this.o.css("display","none")};f.prototype.db=function(b){return this.o.css({display:"block",
position:"absolute",top:b.pageY-state.w,left:b.pageX-state.v})};f.prototype.O=function(b){state.stack=[];this.map.l(p(function(a){if(a&&a.t)return a.ya(r)},this));state.type="normal";$("body").css("cursor",this.a.M);this.sa(b);this.Ba();return this.d.aa(o)};f.prototype.Ba=function(){var b;b=0;this.map.l(p(function(a,c,d,e){if(!(a===q||a.t))if(e>b)return b=e},this));return this.e.css({"margin-top":-50+(-5+b)*this.d.a.r})};f.prototype.p=function(b){return function(a){if(a.originalEvent.touches&&a.originalEvent.touches[0]){a.pageX=
a.originalEvent.touches[0].pageX;a.pageY=a.originalEvent.touches[0].pageY}return b(a)}};return f}();A=function(){function f(b,a){var c,d,e,g,i,h,k;this.d=b;if(a==q)a={};this.a={};i=f.j;for(d in i)this.a[d]=a[d]||f.j[d];d=$(this.a.Xa);k=u.X;for(h in k){e=u.ea(h);e.ab(0.4);i=document.createElement("canvas");i.width=this.d.a.b;i.height=this.d.a.b;c=i.getContext("2d");this.d.Z(c,e);c=$("<img>");c.data("type",h);c.attr("src",i.toDataURL());d.append(c);g=this.a.Aa;c.bind("mousedown",function(j){j={v:j.pageX-
$(this).offset().left,w:j.pageY-$(this).offset().top};e=u.ea($(this).data("type"));return g([e],j)});c.bind("touchstart",function(j){var m;if(j.originalEvent.touches.length){m={v:j.originalEvent.touches[0].pageX-$(this).offset().left,w:j.originalEvent.touches[0].pageY-$(this).offset().top};e=u.ea($(this).data("type"));g([e],m);return j.preventDefault()}});b=this.d;c.bind("mousemove",function(j){var m;if(state.type==="normal"){m=j.pageX-$(this).offset().left;j=j.pageY-$(this).offset().top;m=b.c("basic",
"hitbox").getContext("2d").getImageData(m,j,1,1);m.data[3]>0?$("body").css("cursor",$.browser.webkit&&"-webkit-grab"||$.browser.ua&&"-moz-grab"||"auto"):$("body").css("cursor","auto");return r}})}}f.j={Xa:"#palette",Aa:function(){},M:q,oa:q,Na:q};return f}();$(document).ready(function(){return this.ba=new y({},p(function(){var f;if(window.location.hash.length>1)try{f=new w;f.Ka(window.location.hash.slice(1),this.ba.map);this.ba.Ba()}catch(b){}return $(".share").bind("click",p(function(){var a;f=new w;
a=f.Ga(this.ba.map);window.location.replace("#"+a);$("#popup input").val(window.location);$("#popup").addClass("visible");return $("#popup #dismiss").bind("click",p(function(){return $("#popup").removeClass("visible")},this))},this))},this))});u=function(){function f(b){var a,c,d;d=this.g={top:[q,0],middle:[q,0],low:[q,0]};for(a in d){c=d[a];this.g[a]=b[a]||c}this.ia()}f.Fa=function(b,a){var c;c=a.f("middle")[0];if(b.f("top")[0]){if(c==="drop-low")return r;if(c==="dive"||c==="exchange"||c==="exchange-alt")return r}return o};
f.ea=function(b,a){if(a==q)a=0;if(!f.X[b])l(Error("Unknown type "+b));return new f(f.X[b],a)};f.prototype.ia=function(){var b,a,c,d;d=this.g;for(b in d){c=d[b];a=c[0];c=c[1];if(a&&!(C.call(f.Components[b],a)>=0))l(Error("Unknown "+b+" type "+a));if(c!==0&&c!==90&&c!==180&&c!==270)l(Error("Rotation must be multiple of 90, was "+a))}d=this.f("top")[0];a=this.f("middle")[0];b=this.f("low")[0];if(d==="crossing-hole"&&a!=="drop-middle"&&a!=="drop-low")l(Error("Top type crossing with hole requires middle type drop, was "+
a));if(d!=="crossing-hole"&&(a==="drop-middle"||a==="drop-low"))l(Error("Middle type drop requires top type crossing with hole, was "+d));if(b&&a==="drop-low")l(Error("Middle type "+a+" is incompatible with low type "+b))};f.prototype.ab=function(b){if(!(0<=b&&b<=1))l(Error("Illegal value for opacity"));return this.opacity=b};f.prototype.za=function(b){this.selected=b};f.prototype.ya=function(b){this.t=b};f.prototype.f=function(b){if(b!=="top"&&b!=="middle"&&b!=="low")l(Error("Unknown property "+
b));return this.g[b]};f.prototype.setProperty=function(b,a,c){var d,e;e=this.f(b)[1];d={};if(c===q)c=e;d[b]=[a,c];return this.ga(d)};f.prototype.ga=function(b){var a,c,d,e;c={};e=this.g;for(a in e){d=e[a];c[a]=b[a]||d}this.ia(c);c=this.g;e=[];for(a in c){d=c[a];e.push(this.g[a]=b[a]||d)}return e};f.prototype.xa=function(){return this.rotate(o)};f.prototype.wa=function(){return this.rotate(r)};f.prototype.rotate=function(b,a,c,d){var e,g,i,h,k,j;if(a==q)a=o;if(c==q)c=o;if(d==q)d=o;h=this.g.top;j=h[0];
k=h[1];g=this.g.middle;h=g[0];i=g[1];e=this.g.low;g=e[0];e=e[1];return b?this.ga({top:a?[j,(k+90)%360]:void 0,middle:c?[h,(i+90)%360]:void 0,low:d?[g,(e+90)%360]:void 0}):this.ga({top:a?[j,(k+270)%360]:void 0,middle:c?[h,(i+270)%360]:void 0,low:d?[g,(e+270)%360]:void 0})};f.prototype.toString=function(){var b,a,c,d,e;a=this.g.top;d=a[0];c=a[1];b=this.g.middle;a=b[0];b=b[1];e=this.g.low;return""+d+c+(""+a+b)+(""+e[0]+e[1])+(""+this.opacity+this.selected)};f.Components={top:["crossing","crossing-hole",
"curve","straight"],middle:["crossing","curve","straight","dive","drop-middle","drop-low","exchange-alt","exchange"],low:["crossing","curve","straight"]};f.X={blank:{},"double-straight":{top:["straight",0],middle:["straight",0]},"curve-straight":{top:["curve",270],middle:["straight",0]},"curve-straight-alt":{top:["curve",180],middle:["straight",0]},"double-curve":{top:["curve",270],middle:["curve",0]},"double-curve-alt":{top:["curve",90],middle:["curve",0]},"curve-exchange":{top:["curve",270],middle:["exchange",
0]},"curve-exchange-alt":{top:["curve",180],middle:["exchange-alt",0]},"straight-exchange":{top:["straight",0],middle:["exchange",0]},"straight-exchange-alt":{top:["straight",0],middle:["exchange-alt",0]},"curve-dive":{top:["curve",270],middle:["dive",0]},"curve-dive-alt":{top:["curve",0],middle:["dive",0]},"crossing-straight":{top:["crossing",270],middle:["straight",0]},"crossing-hole":{top:["crossing-hole",270],middle:["drop-middle",0]},"crossing-hole-alt":{top:["crossing-hole",270],middle:["drop-low",
0]}};return f}()}).call(this);
